---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      control-image:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /workdir
    schedule:
      interval: weekly
    groups:
      control-toolchain:
        patterns:
          - "*"
