---
nfs_namespace: nfs-storage
nfs_provisioner_name: nfs-subdir-external-provisioner
nfs_provisioner_image: >-
  {{ platform_release_catalog.storage.nfs_provisioner_image }}
nfs_server: "{{ hostvars[groups['master'] | first].ansible_host }}"
nfs_path: "/mnt/nfs-ssd"
storage_class_name: "raspi-nfs-provisioner"
kubeconfig_local_path: /home/ansible/.kube/config
set_storageclass_default: true
