---
- name: Shutdown all Raspberry Pi nodes
  hosts: cluster
  become: true
  gather_facts: false

  tasks:
    - name: Shut down the system
      ansible.builtin.command: shutdown -h now
      async: 0
      poll: 0
      changed_when: true
      failed_when: false
