---
- name: Prepare Raspberry Pi nodes for Kubernetes cluster
  hosts: all
  become: true
  gather_facts: true
  serial: 1

  roles:
    - role: common
    - role: user_management
      tasks_from: remove.yml
    - role: hostname
    - role: hostsfile
    - role: ssh_setup
      when: cluster_enable_node_mesh_ssh | bool
    - role: k8s_prereq
