---
- name: Deploy lightweight monitoring stack (Prometheus + Grafana + Exporters)
  hosts: localhost
  gather_facts: false

  roles:
    - prometheus
    - node-exporter
    - kube-state-metrics
    - grafana
   # - alertmanager
