
---

- name: Stop NFS server to release disk (if running)
  systemd:
    name: nfs-server
    state: stopped
  when: nfs_format_device | bool
  become: true
  ignore_errors: true  # por si no está instalado aún

- name: Unmount volume if mounted
  mount:
    path: "{{ nfs_export_mount }}"
    state: absent
  when: nfs_format_device | bool
  become: true

- name: Format device with ext4
  filesystem:
    fstype: ext4
    dev: "{{ nfs_export_device }}"
    force: true
  when: nfs_format_device | bool
  become: true
