---
- name: Install base system tools
  ansible.builtin.apt:
    name: "{{ common_required_packages }}"
    state: present
  tags: tools

- name: Install optional administration tools
  ansible.builtin.apt:
    name: "{{ common_admin_packages }}"
    state: present
  when: common_install_admin_tools | bool
  tags: tools
