- name: Create kube-state-metrics ServiceAccount
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'rbac-serviceaccount.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_local_path }}"

- name: Create kube-state-metrics ClusterRole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'rbac-clusterrole.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_local_path }}"

- name: Create kube-state-metrics ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'rbac-clusterrolebinding.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_local_path }}"
