[master]
raspi-master ansible_host=192.168.0.100 ansible_user=admin

[workers]
raspi-worker1 ansible_host=192.168.0.101 ansible_user=admin
raspi-worker2 ansible_host=192.168.0.102 ansible_user=admin
raspi-worker3 ansible_host=192.168.0.103 ansible_user=admin

[control_plane:children]
master

[cluster:children]
master
workers
