---
- name: Include MetalLB installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Include MetalLB verification tasks
  ansible.builtin.import_tasks: verify.yml

- name: Include MetalLB configuration tasks
  ansible.builtin.import_tasks: config.yml

- name: Include MetalLB echo test tasks
  ansible.builtin.import_tasks: echo-test.yml
