---
- name: Create namespace for registry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ registry_namespace }}"
    kubeconfig: "{{ kubeconfig_local_path }}"
  delegate_to: localhost

- name: Create registry PVC when persistence is enabled
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'registry-pvc.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_local_path }}"
  when: registry_persistence_enabled | bool
  delegate_to: localhost

- name: Deploy registry
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'registry-deployment.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_local_path }}"
  delegate_to: localhost

- name: Create registry service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'registry-service.yml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig_local_path }}"
  delegate_to: localhost
