- name: Fetch SSH public key to control host
  fetch:
    src: "/home/{{ ansible_user }}/.ssh/id_ed25519.pub"
    dest: "/home/ansible/.ssh/{{ inventory_hostname }}_ed25519.pub"
    flat: true
  become: true

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Remove old keys from other cluster nodes
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    regexp: "{{ item }}"
    state: absent
  loop: >
    {{ groups['cluster'] | difference([inventory_hostname]) | map('regex_escape') | list }}
  become: true

- name: Authorize public keys from other nodes
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '/home/ansible/.ssh/' + item + '_ed25519.pub') }}"
    state: present
    manage_dir: false
  loop: "{{ groups['cluster'] | difference([inventory_hostname]) }}"
  become: true
