- name: Check SSH connectivity to other nodes
  shell: >
    ssh -i /home/{{ ansible_user }}/.ssh/id_ed25519
    -o BatchMode=yes
    -o ConnectTimeout=3
    -o StrictHostKeyChecking=no
    -l {{ ansible_user }} {{ item }} 'echo OK'
  loop: "{{ groups['cluster'] | difference([inventory_hostname]) }}"
  register: ssh_check
  changed_when: false
