---
containerd_version: "{{ platform_release_catalog.runtime.containerd_version }}"
runc_version: "{{ platform_release_catalog.runtime.runc_version }}"
cni_plugins_version: "{{ platform_release_catalog.runtime.cni_plugins_version }}"

pause_image: "{{ platform_release_catalog.runtime.pause_image }}"

containerd_checksums: "{{ platform_release_catalog.runtime.containerd_checksums }}"
containerd_service_checksum: "{{ platform_release_catalog.runtime.containerd_service_checksum }}"
runc_checksums: "{{ platform_release_catalog.runtime.runc_checksums }}"
cni_plugins_checksums: "{{ platform_release_catalog.runtime.cni_plugins_checksums }}"

containerd_service_url: >-
  https://raw.githubusercontent.com/containerd/containerd/v{{ containerd_version }}/containerd.service
containerd_base_url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}"
runc_url_base: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}"
cni_plugins_url_base: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}"
containerd_version_marker_dir: /var/lib/ansible-k8s-runtime
