---
metrics_server_compatibility_minor_version: auto
metrics_server_default_image: >-
  {{
    platform_release_catalog.observability.metrics_server_images[
      platform_release_catalog.kubernetes.install_version.split('.')[:2] | join('.')
    ]
  }}
metrics_server_supported_images: >-
  {{ platform_release_catalog.observability.metrics_server_images }}
metrics_server_kubelet_insecure_tls: true
metrics_server_metric_resolution: 15s
metrics_server_replicas: 1
metrics_server_cpu_request: 100m
metrics_server_memory_request: 200Mi
metrics_server_cpu_limit: 300m
metrics_server_memory_limit: 300Mi
metrics_server_probe_timeout_seconds: 5
metrics_server_startup_failure_threshold: 24
