---
kubeconfig_local_path: /home/ansible/.kube/config
metallb_namespace: metallb-system
metallb_version: "{{ platform_release_catalog.networking.metallb_version }}"
metallb_manifest_url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
metallb_manifest_checksum: "{{ platform_release_catalog.networking.metallb_manifest_checksum }}"
metallb_manifest_path: /tmp/metallb-native.yaml

metallb_address_pool:
  name: default
  addresses:
    - 192.168.0.240-192.168.0.250
