---
- name: Ensure local kubeconfig directory exists
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ kubeconfig_local_path | dirname }}"
    state: directory
    mode: '0755'

- name: Fetch kubeconfig (admin.conf) to control node
  ansible.builtin.fetch:
    src: "{{ kubeconfig_path }}"
    dest: "{{ kubeconfig_local_path }}"
    flat: true
